name: doc deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: set git env
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # set git infomation
          git config --global user.name 'liangyongrui'
          git config --global user.email 'leungyongrui@gmail.com'

      - name: build
        run: |
          npm i -g docsite
          npm i
          docsite build

      - name: check out page
        run: |
          git clone -b gh-pages git@github.com:XiaoMi/thain.git

      - name: clean and copy
        run: |
          rm -rf thain/*
          cp -R -f {build,img,zh-cn,en-us,index.html,404.html} thain
      
      - name: push
        run: |
          cd thain
          git add .
          git commit -am 'update doc'
          git push -f